<a href="https://colab.research.google.com/github/NewTorPG/muffin-cupcake/blob/master/LDA-Muffin-Cupcakes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [3]:
recipes = pd.read_csv('https://raw.githubusercontent.com/NewTorPG/muffin-cupcake/master/recipes_muffins_cupcakes.csv')
recipes

       Type  Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0    Muffin     55    28      3       7    5              2        0     0
1    Muffin     47    24     12       6    9              1        0     0
2    Muffin     47    23     18       6    4              1        0     0
3    Muffin     45    11     17      17    8              1        0     0
4    Muffin     50    25     12       6    5              2        1     0
5    Muffin     55    27      3       7    5              2        1     0
6    Muffin     54    27      7       5    5              2        0     0
7    Muffin     47    26     10      10    4              1        0     0
8    Muffin     50    17     17       8    6              1        0     0
9    Muffin     50    17     17      11    4              1        0     0
10  Cupcake     39     0     26      19   14              1        1     0
11  Cupcake     42    21     16      10    8              3        0     0
12  Cupcake     34    17     20      20    5              2        1     0
13  Cupcake     39    13     17      19   10              1        1     0
14  Cupcake     38    15     23      15    8              0        1     0
15  Cupcake     42    18     25       9    5              1        0     0
16  Cupcake     36    14     21      14   11              2        1     0
17  Cupcake     38    15     31       8    6              1        1     0
18  Cupcake     36    16     24      12    9              1        1     0
19  Cupcake     34    17     23      11   13              0        1     0

In [4]:
ingredients = recipes[['Flour', 'Milk', 'Sugar', 'Butter', 'Egg', 'Baking Powder', 'Vanilla', 'Salt']].values
ingredients

array([[55, 28,  3,  7,  5,  2,  0,  0],
       [47, 24, 12,  6,  9,  1,  0,  0],
       [47, 23, 18,  6,  4,  1,  0,  0],
       [45, 11, 17, 17,  8,  1,  0,  0],
       [50, 25, 12,  6,  5,  2,  1,  0],
       [55, 27,  3,  7,  5,  2,  1,  0],
       [54, 27,  7,  5,  5,  2,  0,  0],
       [47, 26, 10, 10,  4,  1,  0,  0],
       [50, 17, 17,  8,  6,  1,  0,  0],
       [50, 17, 17, 11,  4,  1,  0,  0],
       [39,  0, 26, 19, 14,  1,  1,  0],
       [42, 21, 16, 10,  8,  3,  0,  0],
       [34, 17, 20, 20,  5,  2,  1,  0],
       [39, 13, 17, 19, 10,  1,  1,  0],
       [38, 15, 23, 15,  8,  0,  1,  0],
       [42, 18, 25,  9,  5,  1,  0,  0],
       [36, 14, 21, 14, 11,  2,  1,  0],
       [38, 15, 31,  8,  6,  1,  1,  0],
       [36, 16, 24, 12,  9,  1,  1,  0],
       [34, 17, 23, 11, 13,  0,  1,  0]])

In [5]:
type_label = np.where(recipes['Type']=='Muffin', 0, 1)
type_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
fold = list(StratifiedKFold(n_splits=10).split(ingredients, type_label))
lda = LDA(n_components=1)
ingriedients = lda.fit_transform(ingredients, type_label)
model = svm.SVC(kernel='linear', C=0.01)
accuracy = cross_val_score(model, ingredients, type_label, cv=fold)
print('average accuracy=%g%%'%(100 * accuracy.mean()))

average accuracy=90%

/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")