<a href="https://colab.research.google.com/github/NewTorPG/muffin-cupcake/blob/master/PCA_Muffin-Cupcakes-Sconse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.decomposition import PCA

In [2]:
recipes = pd.read_csv('https://raw.githubusercontent.com/NewTorPG/muffin-cupcake/master/recipes_muffins_cupcakes_scones.csv')
recipes

       Type  Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0    Muffin     55    28      3       7    5              2        0     0
1    Muffin     47    24     12       6    9              1        0     0
2    Muffin     47    23     18       6    4              1        0     0
3    Muffin     45    11     17      17    8              1        0     0
4    Muffin     50    25     12       6    5              2        1     0
5    Muffin     55    27      3       7    5              2        1     0
6    Muffin     54    27      7       5    5              2        0     0
7    Muffin     47    26     10      10    4              1        0     0
8    Muffin     50    17     17       8    6              1        0     0
9    Muffin     50    17     17      11    4              1        0     0
10  Cupcake     39     0     26      19   14              1        1     0
11  Cupcake     42    21     16      10    8              3        0     0
12  Cupcake     34    17     20      20    5              2        1     0
13  Cupcake     39    13     17      19   10              1        1     0
14  Cupcake     38    15     23      15    8              0        1     0
15  Cupcake     42    18     25       9    5              1        0     0
16  Cupcake     36    14     21      14   11              2        1     0
17  Cupcake     38    15     31       8    6              1        1     0
18  Cupcake     36    16     24      12    9              1        1     0
19  Cupcake     34    17     23      11   13              0        1     0
20    Scone     29     3     46       6    0             11        0     6
21    Scone     19     3     36       3   14              7       14     5
22    Scone     20     5     52       5   10              3        0     5
23    Scone     19     6     50       5    6             10        0     3
24    Scone     19    10     51       5    0             10        0     5

In [3]:
ingredients = recipes[['Flour', 'Milk', 'Sugar', 'Butter', 'Egg', 'Baking Powder', 'Vanilla', 'Salt']].values
ingredients

array([[55, 28,  3,  7,  5,  2,  0,  0],
       [47, 24, 12,  6,  9,  1,  0,  0],
       [47, 23, 18,  6,  4,  1,  0,  0],
       [45, 11, 17, 17,  8,  1,  0,  0],
       [50, 25, 12,  6,  5,  2,  1,  0],
       [55, 27,  3,  7,  5,  2,  1,  0],
       [54, 27,  7,  5,  5,  2,  0,  0],
       [47, 26, 10, 10,  4,  1,  0,  0],
       [50, 17, 17,  8,  6,  1,  0,  0],
       [50, 17, 17, 11,  4,  1,  0,  0],
       [39,  0, 26, 19, 14,  1,  1,  0],
       [42, 21, 16, 10,  8,  3,  0,  0],
       [34, 17, 20, 20,  5,  2,  1,  0],
       [39, 13, 17, 19, 10,  1,  1,  0],
       [38, 15, 23, 15,  8,  0,  1,  0],
       [42, 18, 25,  9,  5,  1,  0,  0],
       [36, 14, 21, 14, 11,  2,  1,  0],
       [38, 15, 31,  8,  6,  1,  1,  0],
       [36, 16, 24, 12,  9,  1,  1,  0],
       [34, 17, 23, 11, 13,  0,  1,  0],
       [29,  3, 46,  6,  0, 11,  0,  6],
       [19,  3, 36,  3, 14,  7, 14,  5],
       [20,  5, 52,  5, 10,  3,  0,  5],
       [19,  6, 50,  5,  6, 10,  0,  3],
       [19, 10, 51,  5,  0, 10,  0,  5]])

In [4]:
type_label = np.where(recipes['Type']=='Muffin', 0, (np.where(recipes['Type']=='Cupcake', 1, 2)))
type_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2])

In [11]:
fold = list(StratifiedKFold(n_splits=5).split(ingredients, type_label))
pca = PCA(n_components=1)
ingriedients = pca.fit_transform(ingredients)
variance = pca.explained_variance_ratio_
model = svm.SVC(kernel='linear', C=0.01)
accuracy = cross_val_score(model, ingredients, type_label, cv=fold)
print('average accuracy=%g%%'%(100 * accuracy.mean()))

average accuracy=96%